In [2]:
import gym
env = gym.make('AirRaid-v0') # try for different environements
observation = env.reset()
env.render()
env.close()

/home/rex/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [36]:
for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(1)
        print(observation, reward, done, info)
        if done:
            print("Finished after {} timesteps".format(t+1))
            break

[-0.00106281  0.02790737  0.02166035 -0.01860084]
[-0.00050467  0.2227121   0.02128834 -0.30437174] 1.0 False {}
[-0.00050467  0.2227121   0.02128834 -0.30437174]
[ 0.00394958  0.4175243   0.0152009  -0.59026553] 1.0 False {}
[ 0.00394958  0.4175243   0.0152009  -0.59026553]
[ 0.01230006  0.61243016  0.00339559 -0.87812164] 1.0 False {}
[ 0.01230006  0.61243016  0.00339559 -0.87812164]
[ 0.02454867  0.8075058  -0.01416684 -1.16973512] 1.0 False {}
[ 0.02454867  0.8075058  -0.01416684 -1.16973512]
[ 0.04069878  1.00280912 -0.03756154 -1.46682561] 1.0 False {}
[ 0.04069878  1.00280912 -0.03756154 -1.46682561]
[ 0.06075496  1.19837024 -0.06689806 -1.77100089] 1.0 False {}
[ 0.06075496  1.19837024 -0.06689806 -1.77100089]
[ 0.08472237  1.39418017 -0.10231807 -2.08371215] 1.0 False {}
[ 0.08472237  1.39418017 -0.10231807 -2.08371215]
[ 0.11260597  1.59017702 -0.14399232 -2.40619891] 1.0 False {}
[ 0.11260597  1.59017702 -0.14399232 -2.40619891]
[ 0.14440951  1.78622968 -0.1921163  -2.739422

In [11]:
! conda update conda
import torch


PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/rex/anaconda3/envs/rl
  package name: conda




ModuleNotFoundError: No module named 'torch'

In [10]:
# env = gym.make("CartPole-v0")
# env.reset()
import torch

ModuleNotFoundError: No module named 'torch'

In [6]:
import notebook
import sys
sys.path.append(['', '/home/rex/anaconda3/envs/rl/lib/python37.zip', '/home/rex/anaconda3/envs/rl/lib/python3.7', '/home/rex/anaconda3/envs/rl/lib/python3.7/lib-dynload', '/home/rex/.local/lib/python3.7/site-packages', '/home/rex/anaconda3/envs/rl/lib/python3.7/site-packages'])

In [1]:
import gym
import numpy as np


done = False
LEARNING_RATE = 0.1
DISCOUNT = 0.95
EPISODES = 25000
SHOW_EVERY = 2000

env = gym.make("MountainCar-v0")
env.reset()

DISCRETE_OS_SIZE = [20, 20] #* len(env.observation_space.high)
discrete_os_win_size = (env.observation_space.high - env.observation_space.low)/DISCRETE_OS_SIZE

q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [env.action_space.n]))

def get_discrete_state(state):
    discrete_state = (state - env.observation_space.low)/discrete_os_win_size
    return tuple(discrete_state.astype(np.int))  # we use this tuple to look up the 3 Q values for the available actions in the q-table

for episode in range(EPISODES):
    discrete_state = get_discrete_state(env.reset())
    done = False
    if episode%SHOW_EVERY == 0:
        print(episode)
        show = True
    else:
        show = False


    while not done:
        action = np.argmax(q_table[discrete_state])
        n_s, reward, done, _ = env.step(action)
        new_discrete_state = get_discrete_state(n_s)
        
        if show:
            env.render()
        if not done:

            max_future_q = np.max(q_table[new_discrete_state])
            current_q = q_table[discrete_state + (action,)]

            new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)
            q_table[discrete_state + (action, )] = new_q

        elif n_s[0] > env.env.goal_position:
            print("we made it on", episode)
            q_table[discrete_state + (action, )] = 0


        # print('.')

        discrete_state = new_discrete_state
#     env.env.close()
    # print('.')
    # env.close()

env.env.close()


0
we made it on 512
we made it on 570
we made it on 576
we made it on 581
we made it on 605
we made it on 609
we made it on 612
we made it on 616
we made it on 644
we made it on 647
we made it on 655
we made it on 658
we made it on 758
we made it on 759
we made it on 760
we made it on 771
we made it on 772
we made it on 774
we made it on 779
we made it on 887
we made it on 889
we made it on 893
we made it on 894
we made it on 896
we made it on 897
we made it on 898
we made it on 899
we made it on 900
we made it on 901
we made it on 902
we made it on 903
we made it on 904
we made it on 905
we made it on 906
we made it on 907
we made it on 908
we made it on 909
we made it on 910
we made it on 911
we made it on 912
we made it on 913
we made it on 914
we made it on 915
we made it on 917
we made it on 918
we made it on 919
we made it on 920
we made it on 921
we made it on 922
we made it on 924
we made it on 925
we made it on 926
we made it on 927
we made it on 928
we made it on 929
we made 

we made it on 1772
we made it on 1773
we made it on 1774
we made it on 1775
we made it on 1776
we made it on 1777
we made it on 1780
we made it on 1781
we made it on 1783
we made it on 1791
we made it on 1799
we made it on 1800
we made it on 1801
we made it on 1803
we made it on 1804
we made it on 1808
we made it on 1812
we made it on 1813
we made it on 1814
we made it on 1815
we made it on 1816
we made it on 1817
we made it on 1818
we made it on 1819
we made it on 1820
we made it on 1821
we made it on 1823
we made it on 1824
we made it on 1825
we made it on 1826
we made it on 1827
we made it on 1828
we made it on 1829
we made it on 1830
we made it on 1831
we made it on 1832
we made it on 1833
we made it on 1834
we made it on 1835
we made it on 1836
we made it on 1837
we made it on 1838
we made it on 1839
we made it on 1840
we made it on 1841
we made it on 1842
we made it on 1843
we made it on 1844
we made it on 1845
we made it on 1846
we made it on 1847
we made it on 1848
we made it o

we made it on 2394
we made it on 2395
we made it on 2396
we made it on 2397
we made it on 2398
we made it on 2399
we made it on 2400
we made it on 2401
we made it on 2402
we made it on 2403
we made it on 2404
we made it on 2406
we made it on 2407
we made it on 2408
we made it on 2409
we made it on 2410
we made it on 2411
we made it on 2412
we made it on 2413
we made it on 2414
we made it on 2415
we made it on 2416
we made it on 2417
we made it on 2418
we made it on 2419
we made it on 2420
we made it on 2421
we made it on 2422
we made it on 2423
we made it on 2424
we made it on 2425
we made it on 2426
we made it on 2427
we made it on 2428
we made it on 2429
we made it on 2430
we made it on 2431
we made it on 2432
we made it on 2433
we made it on 2434
we made it on 2435
we made it on 2436
we made it on 2437
we made it on 2438
we made it on 2440
we made it on 2441
we made it on 2442
we made it on 2443
we made it on 2444
we made it on 2445
we made it on 2446
we made it on 2447
we made it o

we made it on 2888
we made it on 2889
we made it on 2890
we made it on 2891
we made it on 2892
we made it on 2893
we made it on 2894
we made it on 2895
we made it on 2896
we made it on 2897
we made it on 2898
we made it on 2899
we made it on 2900
we made it on 2901
we made it on 2902
we made it on 2903
we made it on 2904
we made it on 2905
we made it on 2906
we made it on 2907
we made it on 2908
we made it on 2909
we made it on 2910
we made it on 2911
we made it on 2912
we made it on 2914
we made it on 2915
we made it on 2916
we made it on 2917
we made it on 2918
we made it on 2919
we made it on 2920
we made it on 2921
we made it on 2922
we made it on 2923
we made it on 2924
we made it on 2926
we made it on 2928
we made it on 2929
we made it on 2930
we made it on 2931
we made it on 2932
we made it on 2933
we made it on 2934
we made it on 2935
we made it on 2936
we made it on 2937
we made it on 2938
we made it on 2939
we made it on 2940
we made it on 2941
we made it on 2942
we made it o

we made it on 3330
we made it on 3331
we made it on 3332
we made it on 3333
we made it on 3334
we made it on 3335
we made it on 3336
we made it on 3337
we made it on 3338
we made it on 3339
we made it on 3340
we made it on 3341
we made it on 3342
we made it on 3343
we made it on 3344
we made it on 3345
we made it on 3346
we made it on 3347
we made it on 3348
we made it on 3349
we made it on 3350
we made it on 3351
we made it on 3352
we made it on 3353
we made it on 3354
we made it on 3355
we made it on 3356
we made it on 3357
we made it on 3358
we made it on 3359
we made it on 3360
we made it on 3361
we made it on 3362
we made it on 3363
we made it on 3364
we made it on 3365
we made it on 3366
we made it on 3367
we made it on 3368
we made it on 3369
we made it on 3370
we made it on 3371
we made it on 3372
we made it on 3373
we made it on 3374
we made it on 3375
we made it on 3376
we made it on 3377
we made it on 3378
we made it on 3379
we made it on 3380
we made it on 3381
we made it o

we made it on 3806
we made it on 3807
we made it on 3808
we made it on 3809
we made it on 3810
we made it on 3811
we made it on 3812
we made it on 3813
we made it on 3814
we made it on 3815
we made it on 3816
we made it on 3817
we made it on 3818
we made it on 3819
we made it on 3820
we made it on 3821
we made it on 3822
we made it on 3823
we made it on 3824
we made it on 3825
we made it on 3826
we made it on 3827
we made it on 3828
we made it on 3829
we made it on 3830
we made it on 3831
we made it on 3832
we made it on 3833
we made it on 3834
we made it on 3835
we made it on 3836
we made it on 3837
we made it on 3838
we made it on 3839
we made it on 3840
we made it on 3841
we made it on 3842
we made it on 3843
we made it on 3844
we made it on 3845
we made it on 3846
we made it on 3847
we made it on 3848
we made it on 3849
we made it on 3850
we made it on 3851
we made it on 3852
we made it on 3853
we made it on 3854
we made it on 3855
we made it on 3856
we made it on 3857
we made it o

we made it on 4270
we made it on 4271
we made it on 4272
we made it on 4273
we made it on 4274
we made it on 4275
we made it on 4276
we made it on 4277
we made it on 4278
we made it on 4279
we made it on 4280
we made it on 4281
we made it on 4282
we made it on 4283
we made it on 4284
we made it on 4285
we made it on 4286
we made it on 4287
we made it on 4288
we made it on 4289
we made it on 4290
we made it on 4291
we made it on 4292
we made it on 4293
we made it on 4294
we made it on 4295
we made it on 4296
we made it on 4297
we made it on 4298
we made it on 4299
we made it on 4300
we made it on 4301
we made it on 4302
we made it on 4303
we made it on 4304
we made it on 4305
we made it on 4306
we made it on 4307
we made it on 4308
we made it on 4309
we made it on 4310
we made it on 4311
we made it on 4313
we made it on 4314
we made it on 4315
we made it on 4316
we made it on 4317
we made it on 4318
we made it on 4319
we made it on 4320
we made it on 4321
we made it on 4324
we made it o

we made it on 4761
we made it on 4762
we made it on 4763
we made it on 4764
we made it on 4765
we made it on 4766
we made it on 4767
we made it on 4768
we made it on 4769
we made it on 4770
we made it on 4771
we made it on 4772
we made it on 4773
we made it on 4774
we made it on 4775
we made it on 4776
we made it on 4777
we made it on 4778
we made it on 4779
we made it on 4780
we made it on 4781
we made it on 4782
we made it on 4783
we made it on 4784
we made it on 4785
we made it on 4786
we made it on 4787
we made it on 4788
we made it on 4789
we made it on 4790
we made it on 4791
we made it on 4792
we made it on 4793
we made it on 4794
we made it on 4795
we made it on 4796
we made it on 4797
we made it on 4798
we made it on 4799
we made it on 4800
we made it on 4801
we made it on 4802
we made it on 4803
we made it on 4804
we made it on 4805
we made it on 4806
we made it on 4807
we made it on 4808
we made it on 4809
we made it on 4810
we made it on 4811
we made it on 4812
we made it o

we made it on 5223
we made it on 5224
we made it on 5225
we made it on 5226
we made it on 5227
we made it on 5228
we made it on 5229
we made it on 5230
we made it on 5231
we made it on 5232
we made it on 5233
we made it on 5234
we made it on 5235
we made it on 5236
we made it on 5237
we made it on 5238
we made it on 5239
we made it on 5240
we made it on 5241
we made it on 5242
we made it on 5243
we made it on 5244
we made it on 5245
we made it on 5246
we made it on 5247
we made it on 5248
we made it on 5249
we made it on 5250
we made it on 5251
we made it on 5252
we made it on 5253
we made it on 5254
we made it on 5255
we made it on 5256
we made it on 5257
we made it on 5258
we made it on 5259
we made it on 5260
we made it on 5261
we made it on 5262
we made it on 5263
we made it on 5264
we made it on 5265
we made it on 5266
we made it on 5267
we made it on 5268
we made it on 5269
we made it on 5270
we made it on 5271
we made it on 5272
we made it on 5273
we made it on 5274
we made it o

we made it on 5725
we made it on 5726
we made it on 5727
we made it on 5728
we made it on 5729
we made it on 5730
we made it on 5731
we made it on 5732
we made it on 5733
we made it on 5734
we made it on 5735
we made it on 5736
we made it on 5737
we made it on 5738
we made it on 5739
we made it on 5740
we made it on 5741
we made it on 5742
we made it on 5743
we made it on 5744
we made it on 5745
we made it on 5746
we made it on 5747
we made it on 5748
we made it on 5749
we made it on 5750
we made it on 5752
we made it on 5753
we made it on 5754
we made it on 5755
we made it on 5756
we made it on 5757
we made it on 5758
we made it on 5759
we made it on 5760
we made it on 5761
we made it on 5762
we made it on 5763
we made it on 5764
we made it on 5765
we made it on 5766
we made it on 5767
we made it on 5768
we made it on 5769
we made it on 5770
we made it on 5771
we made it on 5772
we made it on 5773
we made it on 5774
we made it on 5775
we made it on 5776
we made it on 5777
we made it o

we made it on 6203
we made it on 6204
we made it on 6205
we made it on 6206
we made it on 6207
we made it on 6208
we made it on 6209
we made it on 6210
we made it on 6211
we made it on 6212
we made it on 6213
we made it on 6214
we made it on 6215
we made it on 6216
we made it on 6217
we made it on 6218
we made it on 6219
we made it on 6220
we made it on 6221
we made it on 6222
we made it on 6223
we made it on 6224
we made it on 6225
we made it on 6226
we made it on 6227
we made it on 6228
we made it on 6229
we made it on 6230
we made it on 6231
we made it on 6232
we made it on 6233
we made it on 6234
we made it on 6235
we made it on 6236
we made it on 6237
we made it on 6238
we made it on 6239
we made it on 6240
we made it on 6241
we made it on 6242
we made it on 6243
we made it on 6244
we made it on 6245
we made it on 6246
we made it on 6247
we made it on 6248
we made it on 6249
we made it on 6250
we made it on 6251
we made it on 6252
we made it on 6253
we made it on 6254
we made it o

we made it on 6720
we made it on 6721
we made it on 6722
we made it on 6723
we made it on 6724
we made it on 6725
we made it on 6726
we made it on 6727
we made it on 6729
we made it on 6730
we made it on 6731
we made it on 6732
we made it on 6733
we made it on 6734
we made it on 6735
we made it on 6736
we made it on 6737
we made it on 6738
we made it on 6739
we made it on 6740
we made it on 6741
we made it on 6742
we made it on 6743
we made it on 6744
we made it on 6745
we made it on 6746
we made it on 6747
we made it on 6748
we made it on 6749
we made it on 6750
we made it on 6751
we made it on 6753
we made it on 6754
we made it on 6755
we made it on 6756
we made it on 6757
we made it on 6758
we made it on 6759
we made it on 6760
we made it on 6761
we made it on 6762
we made it on 6763
we made it on 6764
we made it on 6765
we made it on 6766
we made it on 6767
we made it on 6768
we made it on 6769
we made it on 6770
we made it on 6771
we made it on 6772
we made it on 6773
we made it o

we made it on 7183
we made it on 7184
we made it on 7185
we made it on 7186
we made it on 7187
we made it on 7188
we made it on 7190
we made it on 7191
we made it on 7192
we made it on 7193
we made it on 7194
we made it on 7195
we made it on 7196
we made it on 7197
we made it on 7198
we made it on 7199
we made it on 7200
we made it on 7201
we made it on 7202
we made it on 7203
we made it on 7204
we made it on 7205
we made it on 7206
we made it on 7207
we made it on 7208
we made it on 7209
we made it on 7210
we made it on 7211
we made it on 7212
we made it on 7213
we made it on 7214
we made it on 7215
we made it on 7216
we made it on 7217
we made it on 7218
we made it on 7219
we made it on 7220
we made it on 7221
we made it on 7222
we made it on 7223
we made it on 7224
we made it on 7225
we made it on 7226
we made it on 7227
we made it on 7228
we made it on 7229
we made it on 7230
we made it on 7231
we made it on 7232
we made it on 7233
we made it on 7234
we made it on 7235
we made it o

we made it on 7636
we made it on 7637
we made it on 7638
we made it on 7639
we made it on 7640
we made it on 7641
we made it on 7642
we made it on 7643
we made it on 7644
we made it on 7645
we made it on 7646
we made it on 7647
we made it on 7648
we made it on 7649
we made it on 7650
we made it on 7651
we made it on 7652
we made it on 7653
we made it on 7654
we made it on 7655
we made it on 7656
we made it on 7657
we made it on 7658
we made it on 7659
we made it on 7660
we made it on 7661
we made it on 7662
we made it on 7663
we made it on 7664
we made it on 7665
we made it on 7666
we made it on 7667
we made it on 7668
we made it on 7669
we made it on 7670
we made it on 7671
we made it on 7672
we made it on 7673
we made it on 7674
we made it on 7675
we made it on 7676
we made it on 7677
we made it on 7678
we made it on 7679
we made it on 7680
we made it on 7681
we made it on 7682
we made it on 7683
we made it on 7684
we made it on 7685
we made it on 7686
we made it on 7687
we made it o

we made it on 8097
we made it on 8098
we made it on 8099
we made it on 8100
we made it on 8101
we made it on 8102
we made it on 8103
we made it on 8104
we made it on 8105
we made it on 8106
we made it on 8107
we made it on 8108
we made it on 8109
we made it on 8110
we made it on 8111
we made it on 8112
we made it on 8113
we made it on 8114
we made it on 8115
we made it on 8116
we made it on 8117
we made it on 8118
we made it on 8119
we made it on 8120
we made it on 8121
we made it on 8122
we made it on 8123
we made it on 8124
we made it on 8125
we made it on 8126
we made it on 8127
we made it on 8128
we made it on 8129
we made it on 8130
we made it on 8131
we made it on 8132
we made it on 8133
we made it on 8134
we made it on 8135
we made it on 8136
we made it on 8137
we made it on 8138
we made it on 8139
we made it on 8140
we made it on 8141
we made it on 8142
we made it on 8143
we made it on 8144
we made it on 8145
we made it on 8146
we made it on 8147
we made it on 8148
we made it o

we made it on 8536
we made it on 8537
we made it on 8538
we made it on 8539
we made it on 8540
we made it on 8541
we made it on 8542
we made it on 8543
we made it on 8544
we made it on 8545
we made it on 8546
we made it on 8547
we made it on 8548
we made it on 8549
we made it on 8550
we made it on 8551
we made it on 8552
we made it on 8553
we made it on 8554
we made it on 8555
we made it on 8556
we made it on 8557
we made it on 8558
we made it on 8559
we made it on 8560
we made it on 8561
we made it on 8562
we made it on 8563
we made it on 8564
we made it on 8565
we made it on 8566
we made it on 8567
we made it on 8568
we made it on 8569
we made it on 8570
we made it on 8571
we made it on 8572
we made it on 8573
we made it on 8574
we made it on 8575
we made it on 8576
we made it on 8577
we made it on 8578
we made it on 8579
we made it on 8580
we made it on 8581
we made it on 8582
we made it on 8583
we made it on 8584
we made it on 8585
we made it on 8586
we made it on 8587
we made it o

we made it on 8987
we made it on 8988
we made it on 8989
we made it on 8990
we made it on 8991
we made it on 8992
we made it on 8993
we made it on 8994
we made it on 8995
we made it on 8996
we made it on 8997
we made it on 8998
we made it on 8999
we made it on 9000
we made it on 9001
we made it on 9002
we made it on 9003
we made it on 9004
we made it on 9005
we made it on 9006
we made it on 9007
we made it on 9008
we made it on 9009
we made it on 9010
we made it on 9011
we made it on 9012
we made it on 9013
we made it on 9014
we made it on 9015
we made it on 9016
we made it on 9017
we made it on 9018
we made it on 9019
we made it on 9020
we made it on 9021
we made it on 9022
we made it on 9023
we made it on 9024
we made it on 9025
we made it on 9026
we made it on 9027
we made it on 9028
we made it on 9029
we made it on 9030
we made it on 9031
we made it on 9032
we made it on 9033
we made it on 9034
we made it on 9035
we made it on 9036
we made it on 9037
we made it on 9038
we made it o

we made it on 9433
we made it on 9434
we made it on 9435
we made it on 9436
we made it on 9437
we made it on 9438
we made it on 9439
we made it on 9440
we made it on 9441
we made it on 9442
we made it on 9443
we made it on 9444
we made it on 9445
we made it on 9446
we made it on 9447
we made it on 9448
we made it on 9449
we made it on 9450
we made it on 9451
we made it on 9452
we made it on 9453
we made it on 9454
we made it on 9455
we made it on 9456
we made it on 9457
we made it on 9458
we made it on 9459
we made it on 9460
we made it on 9461
we made it on 9462
we made it on 9463
we made it on 9464
we made it on 9465
we made it on 9466
we made it on 9467
we made it on 9468
we made it on 9469
we made it on 9470
we made it on 9471
we made it on 9472
we made it on 9473
we made it on 9474
we made it on 9475
we made it on 9476
we made it on 9477
we made it on 9478
we made it on 9479
we made it on 9480
we made it on 9481
we made it on 9482
we made it on 9483
we made it on 9484
we made it o

we made it on 9874
we made it on 9875
we made it on 9876
we made it on 9877
we made it on 9878
we made it on 9879
we made it on 9880
we made it on 9881
we made it on 9882
we made it on 9883
we made it on 9884
we made it on 9885
we made it on 9886
we made it on 9887
we made it on 9888
we made it on 9889
we made it on 9890
we made it on 9891
we made it on 9892
we made it on 9893
we made it on 9894
we made it on 9895
we made it on 9896
we made it on 9897
we made it on 9898
we made it on 9899
we made it on 9900
we made it on 9901
we made it on 9902
we made it on 9903
we made it on 9904
we made it on 9905
we made it on 9906
we made it on 9907
we made it on 9908
we made it on 9909
we made it on 9910
we made it on 9911
we made it on 9912
we made it on 9913
we made it on 9914
we made it on 9915
we made it on 9916
we made it on 9917
we made it on 9918
we made it on 9919
we made it on 9920
we made it on 9921
we made it on 9922
we made it on 9923
we made it on 9924
we made it on 9925
we made it o

we made it on 10291
we made it on 10292
we made it on 10293
we made it on 10294
we made it on 10295
we made it on 10296
we made it on 10297
we made it on 10298
we made it on 10299
we made it on 10300
we made it on 10301
we made it on 10302
we made it on 10303
we made it on 10304
we made it on 10305
we made it on 10306
we made it on 10307
we made it on 10308
we made it on 10309
we made it on 10310
we made it on 10311
we made it on 10312
we made it on 10313
we made it on 10314
we made it on 10315
we made it on 10316
we made it on 10317
we made it on 10318
we made it on 10319
we made it on 10320
we made it on 10321
we made it on 10322
we made it on 10323
we made it on 10324
we made it on 10325
we made it on 10326
we made it on 10327
we made it on 10328
we made it on 10329
we made it on 10330
we made it on 10331
we made it on 10332
we made it on 10333
we made it on 10334
we made it on 10335
we made it on 10336
we made it on 10337
we made it on 10338
we made it on 10339
we made it on 10340


we made it on 10726
we made it on 10727
we made it on 10728
we made it on 10729
we made it on 10730
we made it on 10731
we made it on 10732
we made it on 10733
we made it on 10734
we made it on 10735
we made it on 10736
we made it on 10737
we made it on 10738
we made it on 10739
we made it on 10740
we made it on 10741
we made it on 10742
we made it on 10743
we made it on 10744
we made it on 10745
we made it on 10746
we made it on 10747
we made it on 10748
we made it on 10749
we made it on 10750
we made it on 10751
we made it on 10752
we made it on 10753
we made it on 10754
we made it on 10755
we made it on 10756
we made it on 10757
we made it on 10758
we made it on 10759
we made it on 10760
we made it on 10761
we made it on 10762
we made it on 10763
we made it on 10764
we made it on 10765
we made it on 10766
we made it on 10767
we made it on 10768
we made it on 10769
we made it on 10770
we made it on 10771
we made it on 10772
we made it on 10773
we made it on 10774
we made it on 10775


we made it on 11173
we made it on 11174
we made it on 11175
we made it on 11176
we made it on 11177
we made it on 11178
we made it on 11179
we made it on 11180
we made it on 11181
we made it on 11182
we made it on 11183
we made it on 11184
we made it on 11185
we made it on 11186
we made it on 11187
we made it on 11188
we made it on 11189
we made it on 11190
we made it on 11191
we made it on 11192
we made it on 11193
we made it on 11194
we made it on 11195
we made it on 11196
we made it on 11197
we made it on 11198
we made it on 11199
we made it on 11200
we made it on 11201
we made it on 11202
we made it on 11203
we made it on 11204
we made it on 11205
we made it on 11206
we made it on 11207
we made it on 11208
we made it on 11209
we made it on 11210
we made it on 11211
we made it on 11212
we made it on 11213
we made it on 11214
we made it on 11215
we made it on 11216
we made it on 11217
we made it on 11218
we made it on 11219
we made it on 11220
we made it on 11221
we made it on 11222


we made it on 11628
we made it on 11629
we made it on 11630
we made it on 11631
we made it on 11632
we made it on 11633
we made it on 11634
we made it on 11635
we made it on 11636
we made it on 11637
we made it on 11638
we made it on 11639
we made it on 11640
we made it on 11641
we made it on 11642
we made it on 11643
we made it on 11644
we made it on 11645
we made it on 11646
we made it on 11647
we made it on 11648
we made it on 11649
we made it on 11650
we made it on 11651
we made it on 11652
we made it on 11653
we made it on 11654
we made it on 11655
we made it on 11656
we made it on 11657
we made it on 11658
we made it on 11659
we made it on 11660
we made it on 11661
we made it on 11662
we made it on 11663
we made it on 11664
we made it on 11665
we made it on 11666
we made it on 11667
we made it on 11668
we made it on 11669
we made it on 11670
we made it on 11671
we made it on 11672
we made it on 11673
we made it on 11674
we made it on 11675
we made it on 11676
we made it on 11677


we made it on 12042
we made it on 12043
we made it on 12044
we made it on 12045
we made it on 12046
we made it on 12047
we made it on 12048
we made it on 12049
we made it on 12050
we made it on 12051
we made it on 12052
we made it on 12053
we made it on 12054
we made it on 12055
we made it on 12056
we made it on 12057
we made it on 12058
we made it on 12059
we made it on 12060
we made it on 12061
we made it on 12062
we made it on 12063
we made it on 12064
we made it on 12065
we made it on 12066
we made it on 12067
we made it on 12068
we made it on 12069
we made it on 12070
we made it on 12071
we made it on 12072
we made it on 12073
we made it on 12074
we made it on 12075
we made it on 12076
we made it on 12077
we made it on 12078
we made it on 12079
we made it on 12080
we made it on 12081
we made it on 12082
we made it on 12083
we made it on 12084
we made it on 12085
we made it on 12086
we made it on 12087
we made it on 12088
we made it on 12089
we made it on 12090
we made it on 12091


we made it on 12456
we made it on 12457
we made it on 12458
we made it on 12459
we made it on 12460
we made it on 12461
we made it on 12462
we made it on 12463
we made it on 12464
we made it on 12465
we made it on 12466
we made it on 12467
we made it on 12468
we made it on 12469
we made it on 12470
we made it on 12471
we made it on 12472
we made it on 12473
we made it on 12474
we made it on 12475
we made it on 12476
we made it on 12477
we made it on 12478
we made it on 12479
we made it on 12480
we made it on 12481
we made it on 12482
we made it on 12483
we made it on 12484
we made it on 12485
we made it on 12486
we made it on 12487
we made it on 12488
we made it on 12489
we made it on 12490
we made it on 12491
we made it on 12492
we made it on 12493
we made it on 12494
we made it on 12495
we made it on 12496
we made it on 12497
we made it on 12498
we made it on 12499
we made it on 12500
we made it on 12501
we made it on 12502
we made it on 12503
we made it on 12504
we made it on 12505


we made it on 12916
we made it on 12917
we made it on 12918
we made it on 12919
we made it on 12920
we made it on 12921
we made it on 12922
we made it on 12923
we made it on 12924
we made it on 12925
we made it on 12926
we made it on 12927
we made it on 12928
we made it on 12929
we made it on 12930
we made it on 12931
we made it on 12932
we made it on 12933
we made it on 12934
we made it on 12935
we made it on 12936
we made it on 12937
we made it on 12938
we made it on 12939
we made it on 12940
we made it on 12941
we made it on 12942
we made it on 12943
we made it on 12944
we made it on 12945
we made it on 12946
we made it on 12947
we made it on 12948
we made it on 12949
we made it on 12950
we made it on 12951
we made it on 12952
we made it on 12953
we made it on 12954
we made it on 12955
we made it on 12956
we made it on 12957
we made it on 12958
we made it on 12959
we made it on 12960
we made it on 12961
we made it on 12962
we made it on 12963
we made it on 12964
we made it on 12965


we made it on 13363
we made it on 13364
we made it on 13365
we made it on 13366
we made it on 13367
we made it on 13368
we made it on 13369
we made it on 13370
we made it on 13371
we made it on 13372
we made it on 13373
we made it on 13374
we made it on 13375
we made it on 13376
we made it on 13377
we made it on 13378
we made it on 13379
we made it on 13380
we made it on 13381
we made it on 13382
we made it on 13383
we made it on 13384
we made it on 13385
we made it on 13386
we made it on 13387
we made it on 13388
we made it on 13389
we made it on 13390
we made it on 13391
we made it on 13392
we made it on 13393
we made it on 13394
we made it on 13395
we made it on 13396
we made it on 13397
we made it on 13398
we made it on 13399
we made it on 13400
we made it on 13401
we made it on 13402
we made it on 13403
we made it on 13404
we made it on 13405
we made it on 13406
we made it on 13407
we made it on 13408
we made it on 13409
we made it on 13410
we made it on 13411
we made it on 13412


we made it on 13818
we made it on 13819
we made it on 13820
we made it on 13821
we made it on 13822
we made it on 13823
we made it on 13824
we made it on 13825
we made it on 13826
we made it on 13827
we made it on 13828
we made it on 13829
we made it on 13830
we made it on 13831
we made it on 13832
we made it on 13833
we made it on 13834
we made it on 13835
we made it on 13836
we made it on 13837
we made it on 13838
we made it on 13839
we made it on 13840
we made it on 13841
we made it on 13842
we made it on 13843
we made it on 13844
we made it on 13845
we made it on 13846
we made it on 13847
we made it on 13848
we made it on 13849
we made it on 13850
we made it on 13851
we made it on 13852
we made it on 13853
we made it on 13854
we made it on 13855
we made it on 13856
we made it on 13857
we made it on 13858
we made it on 13859
we made it on 13860
we made it on 13861
we made it on 13862
we made it on 13863
we made it on 13864
we made it on 13865
we made it on 13866
we made it on 13867


we made it on 14237
we made it on 14238
we made it on 14239
we made it on 14240
we made it on 14241
we made it on 14242
we made it on 14243
we made it on 14244
we made it on 14245
we made it on 14246
we made it on 14247
we made it on 14248
we made it on 14249
we made it on 14250
we made it on 14251
we made it on 14252
we made it on 14253
we made it on 14254
we made it on 14255
we made it on 14256
we made it on 14257
we made it on 14258
we made it on 14259
we made it on 14260
we made it on 14261
we made it on 14262
we made it on 14263
we made it on 14264
we made it on 14265
we made it on 14266
we made it on 14267
we made it on 14268
we made it on 14269
we made it on 14270
we made it on 14271
we made it on 14272
we made it on 14273
we made it on 14274
we made it on 14275
we made it on 14276
we made it on 14277
we made it on 14278
we made it on 14279
we made it on 14280
we made it on 14281
we made it on 14282
we made it on 14283
we made it on 14284
we made it on 14285
we made it on 14286


we made it on 14673
we made it on 14674
we made it on 14675
we made it on 14676
we made it on 14677
we made it on 14678
we made it on 14679
we made it on 14680
we made it on 14681
we made it on 14682
we made it on 14683
we made it on 14684
we made it on 14685
we made it on 14686
we made it on 14687
we made it on 14688
we made it on 14689
we made it on 14690
we made it on 14691
we made it on 14692
we made it on 14693
we made it on 14694
we made it on 14695
we made it on 14696
we made it on 14697
we made it on 14698
we made it on 14699
we made it on 14700
we made it on 14701
we made it on 14702
we made it on 14703
we made it on 14704
we made it on 14705
we made it on 14706
we made it on 14707
we made it on 14708
we made it on 14709
we made it on 14710
we made it on 14711
we made it on 14712
we made it on 14713
we made it on 14714
we made it on 14715
we made it on 14716
we made it on 14717
we made it on 14718
we made it on 14719
we made it on 14720
we made it on 14721
we made it on 14722


we made it on 15091
we made it on 15092
we made it on 15093
we made it on 15094
we made it on 15095
we made it on 15096
we made it on 15097
we made it on 15098
we made it on 15099
we made it on 15100
we made it on 15101
we made it on 15102
we made it on 15103
we made it on 15104
we made it on 15105
we made it on 15106
we made it on 15107
we made it on 15108
we made it on 15109
we made it on 15110
we made it on 15111
we made it on 15112
we made it on 15113
we made it on 15114
we made it on 15115
we made it on 15116
we made it on 15117
we made it on 15118
we made it on 15119
we made it on 15120
we made it on 15121
we made it on 15122
we made it on 15123
we made it on 15124
we made it on 15125
we made it on 15126
we made it on 15127
we made it on 15128
we made it on 15129
we made it on 15130
we made it on 15131
we made it on 15132
we made it on 15133
we made it on 15134
we made it on 15135
we made it on 15136
we made it on 15137
we made it on 15138
we made it on 15139
we made it on 15140


we made it on 15546
we made it on 15547
we made it on 15548
we made it on 15549
we made it on 15550
we made it on 15551
we made it on 15552
we made it on 15553
we made it on 15554
we made it on 15555
we made it on 15556
we made it on 15557
we made it on 15558
we made it on 15559
we made it on 15560
we made it on 15561
we made it on 15562
we made it on 15563
we made it on 15564
we made it on 15565
we made it on 15566
we made it on 15567
we made it on 15568
we made it on 15569
we made it on 15570
we made it on 15571
we made it on 15572
we made it on 15573
we made it on 15574
we made it on 15575
we made it on 15576
we made it on 15577
we made it on 15578
we made it on 15579
we made it on 15580
we made it on 15581
we made it on 15582
we made it on 15583
we made it on 15584
we made it on 15585
we made it on 15586
we made it on 15587
we made it on 15588
we made it on 15589
we made it on 15590
we made it on 15591
we made it on 15592
we made it on 15593
we made it on 15594
we made it on 15595


we made it on 15959
we made it on 15960
we made it on 15961
we made it on 15962
we made it on 15963
we made it on 15964
we made it on 15965
we made it on 15966
we made it on 15967
we made it on 15968
we made it on 15969
we made it on 15970
we made it on 15971
we made it on 15972
we made it on 15973
we made it on 15974
we made it on 15975
we made it on 15976
we made it on 15977
we made it on 15978
we made it on 15979
we made it on 15980
we made it on 15981
we made it on 15982
we made it on 15983
we made it on 15984
we made it on 15985
we made it on 15986
we made it on 15987
we made it on 15988
we made it on 15989
we made it on 15990
we made it on 15991
we made it on 15992
we made it on 15993
we made it on 15994
we made it on 15995
we made it on 15996
we made it on 15997
we made it on 15998
we made it on 15999
16000
we made it on 16000
we made it on 16001
we made it on 16002
we made it on 16003
we made it on 16004
we made it on 16005
we made it on 16006
we made it on 16007
we made it on 

we made it on 16404
we made it on 16405
we made it on 16406
we made it on 16407
we made it on 16408
we made it on 16409
we made it on 16410
we made it on 16411
we made it on 16412
we made it on 16413
we made it on 16414
we made it on 16415
we made it on 16416
we made it on 16417
we made it on 16418
we made it on 16419
we made it on 16420
we made it on 16421
we made it on 16422
we made it on 16423
we made it on 16424
we made it on 16425
we made it on 16426
we made it on 16427
we made it on 16428
we made it on 16429
we made it on 16430
we made it on 16431
we made it on 16432
we made it on 16433
we made it on 16434
we made it on 16435
we made it on 16436
we made it on 16437
we made it on 16438
we made it on 16439
we made it on 16440
we made it on 16441
we made it on 16442
we made it on 16443
we made it on 16444
we made it on 16445
we made it on 16446
we made it on 16447
we made it on 16448
we made it on 16449
we made it on 16450
we made it on 16451
we made it on 16452
we made it on 16453


we made it on 16861
we made it on 16862
we made it on 16863
we made it on 16864
we made it on 16865
we made it on 16866
we made it on 16867
we made it on 16868
we made it on 16869
we made it on 16870
we made it on 16871
we made it on 16872
we made it on 16873
we made it on 16874
we made it on 16875
we made it on 16876
we made it on 16877
we made it on 16878
we made it on 16879
we made it on 16880
we made it on 16881
we made it on 16882
we made it on 16883
we made it on 16884
we made it on 16885
we made it on 16886
we made it on 16887
we made it on 16888
we made it on 16889
we made it on 16890
we made it on 16891
we made it on 16892
we made it on 16893
we made it on 16894
we made it on 16895
we made it on 16896
we made it on 16897
we made it on 16898
we made it on 16899
we made it on 16900
we made it on 16901
we made it on 16902
we made it on 16903
we made it on 16904
we made it on 16905
we made it on 16906
we made it on 16907
we made it on 16908
we made it on 16909
we made it on 16910


we made it on 17310
we made it on 17311
we made it on 17312
we made it on 17313
we made it on 17314
we made it on 17315
we made it on 17316
we made it on 17317
we made it on 17318
we made it on 17319
we made it on 17320
we made it on 17321
we made it on 17322
we made it on 17323
we made it on 17324
we made it on 17325
we made it on 17326
we made it on 17327
we made it on 17328
we made it on 17329
we made it on 17330
we made it on 17331
we made it on 17332
we made it on 17333
we made it on 17334
we made it on 17335
we made it on 17336
we made it on 17337
we made it on 17338
we made it on 17339
we made it on 17340
we made it on 17341
we made it on 17342
we made it on 17343
we made it on 17344
we made it on 17345
we made it on 17346
we made it on 17347
we made it on 17348
we made it on 17349
we made it on 17350
we made it on 17351
we made it on 17352
we made it on 17353
we made it on 17354
we made it on 17355
we made it on 17356
we made it on 17357
we made it on 17358
we made it on 17359


we made it on 17768
we made it on 17769
we made it on 17770
we made it on 17771
we made it on 17772
we made it on 17773
we made it on 17774
we made it on 17775
we made it on 17776
we made it on 17777
we made it on 17778
we made it on 17779
we made it on 17780
we made it on 17781
we made it on 17782
we made it on 17783
we made it on 17784
we made it on 17785
we made it on 17786
we made it on 17787
we made it on 17788
we made it on 17789
we made it on 17790
we made it on 17791
we made it on 17792
we made it on 17793
we made it on 17794
we made it on 17795
we made it on 17796
we made it on 17797
we made it on 17798
we made it on 17799
we made it on 17800
we made it on 17801
we made it on 17802
we made it on 17803
we made it on 17804
we made it on 17805
we made it on 17806
we made it on 17807
we made it on 17808
we made it on 17809
we made it on 17810
we made it on 17811
we made it on 17812
we made it on 17813
we made it on 17814
we made it on 17815
we made it on 17816
we made it on 17817


we made it on 18204
we made it on 18205
we made it on 18206
we made it on 18207
we made it on 18208
we made it on 18209
we made it on 18210
we made it on 18211
we made it on 18212
we made it on 18213
we made it on 18214
we made it on 18215
we made it on 18216
we made it on 18217
we made it on 18218
we made it on 18219
we made it on 18220
we made it on 18221
we made it on 18222
we made it on 18223
we made it on 18224
we made it on 18225
we made it on 18226
we made it on 18227
we made it on 18228
we made it on 18229
we made it on 18230
we made it on 18231
we made it on 18232
we made it on 18233
we made it on 18234
we made it on 18235
we made it on 18236
we made it on 18237
we made it on 18238
we made it on 18239
we made it on 18240
we made it on 18241
we made it on 18242
we made it on 18243
we made it on 18244
we made it on 18245
we made it on 18246
we made it on 18247
we made it on 18248
we made it on 18249
we made it on 18250
we made it on 18251
we made it on 18252
we made it on 18253


we made it on 18661
we made it on 18662
we made it on 18663
we made it on 18664
we made it on 18665
we made it on 18666
we made it on 18667
we made it on 18668
we made it on 18669
we made it on 18670
we made it on 18671
we made it on 18672
we made it on 18673
we made it on 18674
we made it on 18675
we made it on 18676
we made it on 18677
we made it on 18678
we made it on 18679
we made it on 18680
we made it on 18681
we made it on 18682
we made it on 18683
we made it on 18684
we made it on 18685
we made it on 18686
we made it on 18687
we made it on 18688
we made it on 18689
we made it on 18690
we made it on 18691
we made it on 18692
we made it on 18693
we made it on 18694
we made it on 18695
we made it on 18696
we made it on 18697
we made it on 18698
we made it on 18699
we made it on 18700
we made it on 18701
we made it on 18702
we made it on 18703
we made it on 18704
we made it on 18705
we made it on 18706
we made it on 18707
we made it on 18708
we made it on 18709
we made it on 18710


we made it on 19121
we made it on 19122
we made it on 19123
we made it on 19124
we made it on 19125
we made it on 19126
we made it on 19127
we made it on 19128
we made it on 19129
we made it on 19130
we made it on 19131
we made it on 19132
we made it on 19133
we made it on 19134
we made it on 19135
we made it on 19136
we made it on 19137
we made it on 19138
we made it on 19139
we made it on 19140
we made it on 19141
we made it on 19142
we made it on 19143
we made it on 19144
we made it on 19145
we made it on 19146
we made it on 19147
we made it on 19148
we made it on 19149
we made it on 19150
we made it on 19151
we made it on 19152
we made it on 19153
we made it on 19154
we made it on 19155
we made it on 19156
we made it on 19157
we made it on 19158
we made it on 19159
we made it on 19160
we made it on 19161
we made it on 19162
we made it on 19163
we made it on 19164
we made it on 19165
we made it on 19166
we made it on 19167
we made it on 19168
we made it on 19169
we made it on 19170


we made it on 19578
we made it on 19579
we made it on 19580
we made it on 19581
we made it on 19582
we made it on 19583
we made it on 19584
we made it on 19585
we made it on 19586
we made it on 19587
we made it on 19588
we made it on 19589
we made it on 19590
we made it on 19591
we made it on 19592
we made it on 19593
we made it on 19594
we made it on 19595
we made it on 19596
we made it on 19597
we made it on 19598
we made it on 19599
we made it on 19600
we made it on 19601
we made it on 19602
we made it on 19603
we made it on 19604
we made it on 19605
we made it on 19606
we made it on 19607
we made it on 19608
we made it on 19609
we made it on 19610
we made it on 19611
we made it on 19612
we made it on 19613
we made it on 19614
we made it on 19615
we made it on 19616
we made it on 19617
we made it on 19618
we made it on 19619
we made it on 19620
we made it on 19621
we made it on 19622
we made it on 19623
we made it on 19624
we made it on 19625
we made it on 19626
we made it on 19627


we made it on 20000
we made it on 20001
we made it on 20002
we made it on 20003
we made it on 20004
we made it on 20005
we made it on 20006
we made it on 20007
we made it on 20008
we made it on 20009
we made it on 20010
we made it on 20011
we made it on 20012
we made it on 20013
we made it on 20014
we made it on 20015
we made it on 20016
we made it on 20017
we made it on 20018
we made it on 20019
we made it on 20020
we made it on 20021
we made it on 20022
we made it on 20023
we made it on 20024
we made it on 20025
we made it on 20026
we made it on 20027
we made it on 20028
we made it on 20029
we made it on 20030
we made it on 20031
we made it on 20032
we made it on 20033
we made it on 20034
we made it on 20035
we made it on 20036
we made it on 20037
we made it on 20038
we made it on 20039
we made it on 20040
we made it on 20041
we made it on 20042
we made it on 20043
we made it on 20044
we made it on 20045
we made it on 20046
we made it on 20047
we made it on 20048
we made it on 20049


we made it on 20434
we made it on 20435
we made it on 20436
we made it on 20437
we made it on 20438
we made it on 20439
we made it on 20440
we made it on 20441
we made it on 20442
we made it on 20443
we made it on 20444
we made it on 20445
we made it on 20446
we made it on 20447
we made it on 20448
we made it on 20449
we made it on 20450
we made it on 20451
we made it on 20452
we made it on 20453
we made it on 20454
we made it on 20455
we made it on 20456
we made it on 20457
we made it on 20458
we made it on 20459
we made it on 20460
we made it on 20461
we made it on 20462
we made it on 20463
we made it on 20464
we made it on 20465
we made it on 20466
we made it on 20467
we made it on 20468
we made it on 20469
we made it on 20470
we made it on 20471
we made it on 20472
we made it on 20473
we made it on 20474
we made it on 20475
we made it on 20476
we made it on 20477
we made it on 20478
we made it on 20479
we made it on 20480
we made it on 20481
we made it on 20482
we made it on 20483


we made it on 20854
we made it on 20855
we made it on 20856
we made it on 20857
we made it on 20858
we made it on 20859
we made it on 20860
we made it on 20861
we made it on 20862
we made it on 20863
we made it on 20864
we made it on 20865
we made it on 20866
we made it on 20867
we made it on 20868
we made it on 20869
we made it on 20870
we made it on 20871
we made it on 20872
we made it on 20873
we made it on 20874
we made it on 20875
we made it on 20876
we made it on 20877
we made it on 20878
we made it on 20879
we made it on 20880
we made it on 20881
we made it on 20882
we made it on 20883
we made it on 20884
we made it on 20885
we made it on 20886
we made it on 20887
we made it on 20888
we made it on 20889
we made it on 20890
we made it on 20891
we made it on 20892
we made it on 20893
we made it on 20894
we made it on 20895
we made it on 20896
we made it on 20897
we made it on 20898
we made it on 20899
we made it on 20900
we made it on 20901
we made it on 20902
we made it on 20903


we made it on 21305
we made it on 21306
we made it on 21307
we made it on 21308
we made it on 21309
we made it on 21310
we made it on 21311
we made it on 21312
we made it on 21313
we made it on 21314
we made it on 21315
we made it on 21316
we made it on 21317
we made it on 21318
we made it on 21319
we made it on 21320
we made it on 21321
we made it on 21322
we made it on 21323
we made it on 21324
we made it on 21325
we made it on 21326
we made it on 21327
we made it on 21328
we made it on 21329
we made it on 21330
we made it on 21331
we made it on 21332
we made it on 21333
we made it on 21334
we made it on 21335
we made it on 21336
we made it on 21337
we made it on 21338
we made it on 21339
we made it on 21340
we made it on 21341
we made it on 21342
we made it on 21343
we made it on 21344
we made it on 21345
we made it on 21346
we made it on 21347
we made it on 21348
we made it on 21349
we made it on 21350
we made it on 21351
we made it on 21352
we made it on 21353
we made it on 21354


we made it on 21736
we made it on 21737
we made it on 21738
we made it on 21739
we made it on 21740
we made it on 21741
we made it on 21742
we made it on 21743
we made it on 21744
we made it on 21745
we made it on 21746
we made it on 21747
we made it on 21748
we made it on 21749
we made it on 21750
we made it on 21751
we made it on 21752
we made it on 21753
we made it on 21754
we made it on 21755
we made it on 21756
we made it on 21757
we made it on 21758
we made it on 21759
we made it on 21760
we made it on 21761
we made it on 21762
we made it on 21763
we made it on 21764
we made it on 21765
we made it on 21766
we made it on 21767
we made it on 21768
we made it on 21769
we made it on 21770
we made it on 21771
we made it on 21772
we made it on 21773
we made it on 21774
we made it on 21775
we made it on 21776
we made it on 21777
we made it on 21778
we made it on 21779
we made it on 21780
we made it on 21781
we made it on 21782
we made it on 21783
we made it on 21784
we made it on 21785


we made it on 22152
we made it on 22153
we made it on 22154
we made it on 22155
we made it on 22156
we made it on 22157
we made it on 22158
we made it on 22159
we made it on 22160
we made it on 22161
we made it on 22162
we made it on 22163
we made it on 22164
we made it on 22165
we made it on 22166
we made it on 22167
we made it on 22168
we made it on 22169
we made it on 22170
we made it on 22171
we made it on 22172
we made it on 22173
we made it on 22174
we made it on 22175
we made it on 22176
we made it on 22177
we made it on 22178
we made it on 22179
we made it on 22180
we made it on 22181
we made it on 22182
we made it on 22183
we made it on 22184
we made it on 22185
we made it on 22186
we made it on 22187
we made it on 22188
we made it on 22189
we made it on 22190
we made it on 22191
we made it on 22192
we made it on 22193
we made it on 22194
we made it on 22195
we made it on 22196
we made it on 22197
we made it on 22198
we made it on 22199
we made it on 22200
we made it on 22201


we made it on 22561
we made it on 22562
we made it on 22563
we made it on 22564
we made it on 22565
we made it on 22566
we made it on 22567
we made it on 22568
we made it on 22569
we made it on 22570
we made it on 22571
we made it on 22572
we made it on 22573
we made it on 22574
we made it on 22575
we made it on 22576
we made it on 22577
we made it on 22578
we made it on 22579
we made it on 22580
we made it on 22581
we made it on 22582
we made it on 22583
we made it on 22584
we made it on 22585
we made it on 22586
we made it on 22587
we made it on 22588
we made it on 22589
we made it on 22590
we made it on 22591
we made it on 22592
we made it on 22593
we made it on 22594
we made it on 22595
we made it on 22596
we made it on 22597
we made it on 22598
we made it on 22599
we made it on 22600
we made it on 22601
we made it on 22602
we made it on 22603
we made it on 22604
we made it on 22605
we made it on 22606
we made it on 22607
we made it on 22608
we made it on 22609
we made it on 22610


we made it on 22975
we made it on 22976
we made it on 22977
we made it on 22978
we made it on 22979
we made it on 22980
we made it on 22981
we made it on 22982
we made it on 22983
we made it on 22984
we made it on 22985
we made it on 22986
we made it on 22987
we made it on 22988
we made it on 22989
we made it on 22990
we made it on 22991
we made it on 22992
we made it on 22993
we made it on 22994
we made it on 22995
we made it on 22996
we made it on 22997
we made it on 22998
we made it on 22999
we made it on 23000
we made it on 23001
we made it on 23002
we made it on 23003
we made it on 23004
we made it on 23005
we made it on 23006
we made it on 23007
we made it on 23008
we made it on 23009
we made it on 23010
we made it on 23011
we made it on 23012
we made it on 23013
we made it on 23014
we made it on 23015
we made it on 23016
we made it on 23017
we made it on 23018
we made it on 23019
we made it on 23020
we made it on 23021
we made it on 23022
we made it on 23023
we made it on 23024


we made it on 23390
we made it on 23391
we made it on 23392
we made it on 23393
we made it on 23394
we made it on 23395
we made it on 23396
we made it on 23397
we made it on 23398
we made it on 23399
we made it on 23400
we made it on 23401
we made it on 23402
we made it on 23403
we made it on 23404
we made it on 23405
we made it on 23406
we made it on 23407
we made it on 23408
we made it on 23409
we made it on 23410
we made it on 23411
we made it on 23412
we made it on 23413
we made it on 23414
we made it on 23415
we made it on 23416
we made it on 23417
we made it on 23418
we made it on 23419
we made it on 23420
we made it on 23421
we made it on 23422
we made it on 23423
we made it on 23424
we made it on 23425
we made it on 23426
we made it on 23427
we made it on 23428
we made it on 23429
we made it on 23430
we made it on 23431
we made it on 23432
we made it on 23433
we made it on 23434
we made it on 23435
we made it on 23436
we made it on 23437
we made it on 23438
we made it on 23439


we made it on 23846
we made it on 23847
we made it on 23848
we made it on 23849
we made it on 23850
we made it on 23851
we made it on 23852
we made it on 23853
we made it on 23854
we made it on 23855
we made it on 23856
we made it on 23857
we made it on 23858
we made it on 23859
we made it on 23860
we made it on 23861
we made it on 23862
we made it on 23863
we made it on 23864
we made it on 23865
we made it on 23866
we made it on 23867
we made it on 23868
we made it on 23869
we made it on 23870
we made it on 23871
we made it on 23872
we made it on 23873
we made it on 23874
we made it on 23875
we made it on 23876
we made it on 23877
we made it on 23878
we made it on 23879
we made it on 23880
we made it on 23881
we made it on 23882
we made it on 23883
we made it on 23884
we made it on 23885
we made it on 23886
we made it on 23887
we made it on 23888
we made it on 23889
we made it on 23890
we made it on 23891
we made it on 23892
we made it on 23893
we made it on 23894
we made it on 23895


we made it on 24295
we made it on 24296
we made it on 24297
we made it on 24298
we made it on 24299
we made it on 24300
we made it on 24301
we made it on 24302
we made it on 24303
we made it on 24304
we made it on 24305
we made it on 24306
we made it on 24307
we made it on 24308
we made it on 24309
we made it on 24310
we made it on 24311
we made it on 24312
we made it on 24313
we made it on 24314
we made it on 24315
we made it on 24316
we made it on 24317
we made it on 24318
we made it on 24319
we made it on 24320
we made it on 24321
we made it on 24322
we made it on 24323
we made it on 24324
we made it on 24325
we made it on 24326
we made it on 24327
we made it on 24328
we made it on 24329
we made it on 24330
we made it on 24331
we made it on 24332
we made it on 24333
we made it on 24334
we made it on 24335
we made it on 24336
we made it on 24337
we made it on 24338
we made it on 24339
we made it on 24340
we made it on 24341
we made it on 24342
we made it on 24343
we made it on 24344


we made it on 24749
we made it on 24750
we made it on 24751
we made it on 24752
we made it on 24753
we made it on 24754
we made it on 24755
we made it on 24756
we made it on 24757
we made it on 24758
we made it on 24759
we made it on 24760
we made it on 24761
we made it on 24762
we made it on 24763
we made it on 24764
we made it on 24765
we made it on 24766
we made it on 24767
we made it on 24768
we made it on 24769
we made it on 24770
we made it on 24771
we made it on 24772
we made it on 24773
we made it on 24774
we made it on 24775
we made it on 24776
we made it on 24777
we made it on 24778
we made it on 24779
we made it on 24780
we made it on 24781
we made it on 24782
we made it on 24783
we made it on 24784
we made it on 24785
we made it on 24786
we made it on 24787
we made it on 24788
we made it on 24789
we made it on 24790
we made it on 24791
we made it on 24792
we made it on 24793
we made it on 24794
we made it on 24795
we made it on 24796
we made it on 24797
we made it on 24798


In [36]:
# objective is to get the cart to the flag.
# for now, let's just move randomly:

import gym
import numpy as np

env = gym.make("MountainCar-v0")

LEARNING_RATE = 0.1

DISCOUNT = 0.95
EPISODES = 25000
SHOW_EVERY = 3000

DISCRETE_OS_SIZE = [20, 20]
discrete_os_win_size = (env.observation_space.high - env.observation_space.low)/DISCRETE_OS_SIZE

# Exploration settings
epsilon = 1  # not a constant, qoing to be decayed
START_EPSILON_DECAYING = 1
END_EPSILON_DECAYING = EPISODES//2
epsilon_decay_value = epsilon/(END_EPSILON_DECAYING - START_EPSILON_DECAYING)


q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [env.action_space.n]))


def get_discrete_state(state):
    discrete_state = (state - env.observation_space.low)/discrete_os_win_size
    return tuple(discrete_state.astype(np.int))  # we use this tuple to look up the 3 Q values for the available actions in the q-table


for episode in range(EPISODES):
    discrete_state = get_discrete_state(env.reset())
    done = False

    if episode % SHOW_EVERY == 0:
        render = True
        print(episode)
    else:
        render = False

    while not done:

        if np.random.random() > epsilon:
            # Get action from Q table
            action = np.argmax(q_table[discrete_state])
        else:
            # Get random action
            action = np.random.randint(0, env.action_space.n)


        new_state, reward, done, _ = env.step(action)

        new_discrete_state = get_discrete_state(new_state)

        if episode % SHOW_EVERY == 0:
            env.render()
        #new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)

        # If simulation did not end yet after last step - update Q table
        if not done:

            # Maximum possible Q value in next step (for new state)
            max_future_q = np.max(q_table[new_discrete_state])

            # Current Q value (for current state and performed action)
            current_q = q_table[discrete_state + (action,)]

            # And here's our equation for a new Q value for current state and action
            new_q = (1 - LEARNING_RATE) * current_q + LEARNING_RATE * (reward + DISCOUNT * max_future_q)

            # Update Q table with new Q value
            q_table[discrete_state + (action,)] = new_q


        # Simulation ended (for any reson) - if goal position is achived - update Q value with reward directly
        elif new_state[0] >= env.goal_position:
            #q_table[discrete_state + (action,)] = reward
            q_table[discrete_state + (action,)] = 0

        discrete_state = new_discrete_state

    # Decaying is being done every episode if episode number is within decaying range
    if END_EPSILON_DECAYING >= episode >= START_EPSILON_DECAYING:
        epsilon -= epsilon_decay_value


env.close()

(12, 10, 3)

In [11]:
env.close()|

SyntaxError: invalid syntax (<ipython-input-11-ed101c7ca3a2>, line 1)

In [12]:
print("Reward Sum on all episodes " + str(sum(rev_list)/epis))
print("Final Values Q-Table")
max(Q[:,2])

Reward Sum on all episodes 0.1508
Final Values Q-Table


0.8529103010915031

In [39]:
env.close()

In [17]:
import gym
import numpy as np 

# 1. Load Environment and Q-table structure
env = gym.make('FrozenLake8x8-v0')
Q = np.zeros([env.observation_space.n,env.action_space.n])
# env.obeservation.n, env.action_space.n gives number of states and action in env loaded

# 2. Parameters of Q-leanring
eta = .628
gma = .9
epis = 5000
rev_list = [] # rewards per episode calculate

# 3. Q-learning Algorithm

# for i in range(epis):
#     # Reset environment
#     s = env.reset()
#     rAll = 0
#     d = False
#     j = 0
#     #The Q-Table learning algorithm
#     while j < 99:
#         env.render()
#         j+=1
#         # Choose action from Q table
#         a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
#         #Get new state & reward from environment
#         s1,r,d,_ = env.step(a)
#         #Update Q-Table with new knowledge
#         Q[s,a] = Q[s,a] + eta*(r + gma*np.max(Q[s1,:]) - Q[s,a])
#         rAll += r
#         s = s1
#         if d == True:
#             break
#     rev_list.append(rAll)
#     env.render()

print("Reward Sum on all episodes " + str(sum(rev_list)/epis))
print("Final Values Q-Table")
# print(Q)
# # Reset environment
# s = env.reset()
# d = False
# # The Q-Table learning algorithm
# while d != True:
#     env.render()
#     # Choose action from Q table
#     a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
#     #Get new state & reward from environment
#     s1,r,d,_ = env.step(a)
#     #Update Q-Table with new knowledge
#     Q[s,a] = Q[s,a] + eta*(r + gma*np.max(Q[s1,:]) - Q[s,a])
#     s = s1
# # Code will stop at d == True, and render one state before it

Reward Sum on all episodes 0.0
Final Values Q-Table


/home/rex/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [8]:
# Reset environment
s = env.reset()
rAll = 0
d = False
j = 0
#The Q-Table learning algorithm
# while j < 99:
#     env.render()
#     j+=1
#     # Choose action from Q table
np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(2+1)))
#     #Get new state & reward from environment
#     s1,r,d,_ = env.step(a)
#     #Update Q-Table with new knowledge
#     Q[s,a] = Q[s,a] + eta*(r + gma*np.max(Q[s1,:]) - Q[s,a])
#     rAll += r
#     s = s1
#     if d == True:
#         break
# rev_list.append(rAll)
# env.render()

# print("Reward Sum on all episodes " + str(sum(rev_list)/epis))
# print("Final Values Q-Table")
# print(Q)

2

In [32]:
env = gym.make("Breakout-v0")

In [33]:
env.action_space.n

4

In [26]:
np.argmax(a)

0

In [31]:
env.step(1.0)

(1, 0.0, False, {'prob': 0.3333333333333333})

In [44]:
import numpy as np
import gym
import matplotlib.pyplot as plt

# Import and initialize Mountain Car Environment
env = gym.make('MountainCar-v0')
env.reset()

# Define Q-learning function
def QLearning(env, learning, discount, epsilon, min_eps, episodes):
    # Determine size of discretized state space
    num_states = (env.observation_space.high - env.observation_space.low)*\
                    np.array([10, 100])
    num_states = np.round(num_states, 0).astype(int) + 1
    
    # Initialize Q table
    Q = np.random.uniform(low = -1, high = 1, 
                          size = (num_states[0], num_states[1], 
                                  env.action_space.n))
    
    # Initialize variables to track rewards
    reward_list = []
    ave_reward_list = []
    
    # Calculate episodic reduction in epsilon
    reduction = (epsilon - min_eps)/episodes
    
    # Run Q learning algorithm
    for i in range(episodes):
        # Initialize parameters
        done = False
        tot_reward, reward = 0,0
        state = env.reset()
        
        # Discretize state
        state_adj = (state - env.observation_space.low)*np.array([10, 100])
        state_adj = np.round(state_adj, 0).astype(int)
    
        while done != True:   
            # Render environment for last five episodes
            if i >= (episodes - 4):
                env.render()
                
            # Determine next action - epsilon greedy strategy
            if np.random.random() < 1 - epsilon:
                action = np.argmax(Q[state_adj[0], state_adj[1]]) 
            else:
                action = np.random.randint(0, env.action_space.n)
                
            # Get next state and reward
            state2, reward, done, info = env.step(action) 
            
            # Discretize state2
            state2_adj = (state2 - env.observation_space.low)*np.array([10, 100])
            state2_adj = np.round(state2_adj, 0).astype(int)
            
            #Allow for terminal states
            if done and state2[0] >= 0.5:
                Q[state_adj[0], state_adj[1], action] = reward
                
            # Adjust Q value for current state
            else:
                delta = learning*(reward + 
                                 discount*np.max(Q[state2_adj[0], 
                                                   state2_adj[1]]) - 
                                 Q[state_adj[0], state_adj[1],action])
                Q[state_adj[0], state_adj[1],action] += delta
                                     
            # Update variables
            tot_reward += reward
            state_adj = state2_adj
        
        # Decay epsilon
        if epsilon > min_eps:
            epsilon -= reduction
        
        # Track rewards
        reward_list.append(tot_reward)
        
        if (i+1) % 100 == 0:
            ave_reward = np.mean(reward_list)
            ave_reward_list.append(ave_reward)
            reward_list = []
            
        if (i+1) % 100 == 0:    
            print('Episode {} Average Reward: {}'.format(i+1, ave_reward))
            
    env.close()
    
    return ave_reward_list

# Run Q-learning algorithm
rewards = QLearning(env, 0.2, 0.9, 0.8, 0, 5000)

# Plot Rewards
plt.plot(100*(np.arange(len(rewards)) + 1), rewards)
plt.xlabel('Episodes')
plt.ylabel('Average Reward')
plt.title('Average Reward vs Episodes')
plt.savefig('rewards.jpg')     
plt.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Episode 100 Average Reward: -200.0
Episode 200 Average Reward: -200.0
Episode 300 Average Reward: -200.0
Episode 400 Average Reward: -200.0
Episode 500 Average Reward: -200.0
Episode 600 Average Reward: -200.0
Episode 700 Average Reward: -200.0
Episode 800 Average Reward: -200.0
Episode 900 Average Reward: -200.0
Episode 1000 Average Reward: -200.0
Episode 1100 Average Reward: -200.0
Episode 1200 Average Reward: -200.0
Episode 1300 Average Reward: -200.0
Episode 1400 Average Reward: -200.0
Episode 1500 Average Reward: -200.0
Episode 1600 Average Reward: -200.0
Episode 1700 Average Reward: -200.0
Episode 1800 Average Reward: -200.0
Episode 1900 Average Reward: -200.0
Episode 2000 Average Reward: -200.0
Episode 2100 Average Reward: -200.0
Episode 2200 Average Reward: -200.0
Episode 2300 Average Reward: -200.0
Episode 2400 Average Reward: -199.74
Episode 2500 Average Reward: -199.45
Episode 